### ISSUE TITLE
Add a website to check user agent using UserAgentInfo.

### ISSUE THREAD

**Issue by quentin389** [quentin389/UserAgentInfo#15]
Several times now I needed to check one user agent using UserAgentInfo, and each time I had to modify my application to do that. Of course it's extremely simple, but still - it would be nicer if I had a website like user-agent-string.info that shows the UA results.

**Comment by iberflow** [comment]
I'm up for contributing and hosting it. I'd find it very useful especially when debugging something that requires parsing the UA. Maybe create a new repo for this?

**Comment by quentin389** [comment]
Yes, i've just added it as an issue to remember to do it.

Thanks for the offer. I'll probably want to do it as a closed source website, to put some Google ads there, but right now I'm not sure if that makes sense. I'll post an update here.
