### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by kevinsteger** [quentin389/UserAgentInfo#17]
There are notes in the readme mentioning weekly updates.  It looks like this has not been updated in some time.  Is there still activity on this?

Thank you.

**Comment by quentin389** [comment]
Hi,
yeah, I haven't updated anything here for a long time. I actually use UserAgentInfo on my website and it still gives almost perfect results, even though there were no updates.
Do you have problem with some specific User Agents, or is that not the reason you're asking?

**Comment by kevinsteger** [comment]
I have not tested.  I was asking because the readme said weekly update and the last update was 9 months.  Thanks for the quick reply!

**Comment by kevinsteger** [comment]
Could you give me an example of how to update this?  I have several user_agents that do not work properly for the ->getDeviceFamily()

This is a Motorola:

Mozilla/5.0 (Linux; Android 4.4; XT1058 Build/13.11.3Q2.X-69-3-8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.92 Mobile Safari/537.36

Samsung:

Mozilla/5.0 (Linux; U; Android 4.1.2; pt-br; GT-S5310B Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Samsung:

Mozilla/5.0 (Linux; U; Android 4.1.2; pt-br; GT-S7392L Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

etc.

I have many that do not show properly.

Thanks.

**Comment by quentin389** [comment]
Device family is actually something I don't use. If that's the issue you have I'll have to perform an update of the libraries.
