### ISSUE TITLE
Project being maintained?

### ISSUE THREAD

**Issue by Austinb** [quentin389/UserAgentInfo#18]
I have been using this library at v1.3 for some time and I see it has not been updated in a long time.  Is this project more or less dead?  If so are there any forks still being updated or other projects being maintained that offer similar functionality?

One major sticking point for me is this library does not support composer which it badly needs to do moving forward (see #4).

**Comment by bishopb** [comment]
Based on the project owner's [contribution graph over the last year](https://github.com/quentin389) I would surmise no, sadly.

**Comment by Austinb** [comment]
That sucks.  Well in case anyone needs help finding a maintained library I switched to another project which also uses https://github.com/serbanghita/Mobile-Detect as its base.  There are other links to other framework implementations.
