### ISSUE TITLE
Can composer be used?

### ISSUE THREAD

**Issue by CMCDragonkai** [quentin389/UserAgentInfo#4]
Hey thanks for the email about this library.

Currently I need a portable solution. That means not needing to use php.ini to point to browsecap. Would it be possible to change browsecap to something other than an ini file or parse it independent from php.ini. This could allow other languages to get involved. Furthermore are you going to add this composer?

**Comment by quentin389** [comment]
Hi, yes, moving away from php.ini browscap is a priority for me right now. I already have sped up GaretJax browscap, so it can fit my needs, and I'm going to  migrate UserAgentInfo to use it in next two weeks (perhaps earlier, but I cannot guarantee that).

What about composer? Are there any substantial benefits of using it? Right now all you need to do is to put one require_once in the code and then you use the static class from anywhere in your code, so there isn't much need for autoloading here. Or could it perhaps help with using a cache with UserAgentInfo?
If you think it may be a good idea to use composer, I'm gonna look into it, but I don't like the idea of adding more bloat to the class if the benefit is not substantial.

**Comment by quentin389** [comment]
Moved request for browscap without php.ini to https://github.com/quentin389/UserAgentInfo/issues/5
This topic changed to a discussion about composer.

**Comment by CMCDragonkai** [comment]
Adding composer doesn't increase bloat. Composer does the autoloading for you if you follow PSR-0 namespacing. Otherwise a simple classmap is possible. It makes it easier to manage versions of releases.

**Comment by CMCDragonkai** [comment]
A programmartic conversion to json might be better.

**Comment by quentin389** [comment]
UserAgentInfo won't have any dependencies once browscap is migrated to phpbrowscap. It also doesn't require autoloading, it takes care of including its files. So the only reason to use composer would be for the updates.

I'm not against making it a composer package, but only if it can install updates from git, and if it can be made optional without forcing `PHP 5.3+` requirement on the whole program.

I will have to test it and see if that can be achieved and if it will work well. If that will be the case then I will add composer.

That's going to have to wait until after the next release, because switching from `get_browser()` to `phpbrowscap` is a priority.

Btw. what do you mean by "A programmartic conversion to json might be better." ? Are you referring to the `browscap.ini` source file?

**Comment by CMCDragonkai** [comment]
Composer can do that fine. It can install from git, but I prefer using tagged releases instead of branches. Yep I would prefer Json mainly because of multilanguage support. I may need to use other programming languages.

**Comment by quentin389** [comment]
I'm not going to use JSON as a source file for any of the parsers. PHP array source file is the way to go, performance wise.

Loading large data structures into PHP memory takes a lot of time. So, when you decode JSON into array of PHP objects, or unserialize array of arrays - it takes time. This time becomes more and more significant the larger the thing you have to load into memory is.
However, when you use `opcache` on production servers, and that something you should definitely be doing, the PHP files you're using become already preloaded into the memory. That doesn't affect json source files behaviour, but when you use a php file with an array as a source for the data and use `require` to load it, the time it previously took to load all that data drops almost to zero.

You can see time differences even for fast classes like `ua-parser` - https://github.com/quentin389/UserAgentInfo/issues/7#issuecomment-23215359
But the difference for `phpbrowscap` between loading from PHP file (as it's doing now) and JSON file is huuuuge.

So, as I take performance as priority in my projects, I will only use PHP files as the source data files.

**Comment by quentin389** [comment]
Migration from php.ini based `get_browser()` to `phpbrowscap` project is now completed.

**Comment by ammont** [comment]
+1 for making it a composer package

**Comment by quentin389** [comment]
I will test the composer this weekend.

**Comment by ammont** [comment]
It'll also manage your dependencies so you don't need to include the 3rd party libs.
